; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitc-1

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.6
	johboh/nlohmann-json@^3.12.0
	bblanchon/ArduinoJson@^7.2.2
monitor_speed = 115200
board_upload.flash_size = 1M
board_build.spiffs_size = 512K
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.1m512.ld
build_flags = -D USE_ESP32=0, -D USE_ESP8266=1, -D ENABLE_SENSOR=1, -D ANALOG_PIN=3

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.6
	johboh/nlohmann-json@^3.12.0
	bblanchon/ArduinoJson@^7.2.2
build_flags = -D USE_ESP32=1, -D USE_ESP8266=0, -D ENABLE_SENSOR=1, -D ANALOG_PIN=3
